baseurl = "https://senyoltw.net/"
title = "senyoltw.net"
theme = "hugo-theme-nix"
languageCode = "ja-jp"
disqusShortname = "senyoltw.net"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 1
    url = "https://senyoltw.hatenablog.jp/"
  [[menu.header]]
    name = "bookmark"
    weight = 0
    url = "https://b.hatena.ne.jp/iuyui/bookmark"
  [[menu.header]]
    name = "src"
    weight = 0
    url = "https://github.com/senyoltw/senyoltw.net"

[params]
  GithubID = "senyoltw"
  TwitterID = "senyoltw"
  InstagramID = "senyoltw"
  Name = "senyoltw"
  HeaderUsername = "senyoltw"
  HeaderHostname = "senyoltw"
  #Email = "your_email"
  About = "せにょーるです。"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"

