baseurl = "http://senyoltw.net/"
title = "senyoltw.net"
theme = "hugo-theme-nix"
languageCode = "ja-jp"
disqusShortname = "senyoltw.net"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "senyoltw"
  TwitterID = "senyoltw"
  #LinkedInID = "your_linkedin"
  #GoogleplusID = "your_googleplus"
  #FacebookID = "your_facebook"
  #TelegramID = "your_telegram"
  Name = "senyoltw"
  HeaderUsername = "senyoltw"
  HeaderHostname = "senyoltw"
  #Email = "your_email"
  About = "せにょーるです。"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
  #SlackURL = "your_slack_invite_url"

