baseurl = "https://senyoltw.net/"
title = "senyoltw.net"
theme = "hugo-theme-nix"
languageCode = "ja-jp"
disqusShortname = "senyoltw.net"

[menu]
  [[menu.header]]
    name = "src"
    weight = 0
    url = "https://github.com/senyoltw/senyoltw.net"

[params]
  BlogURL = "https://senyoltw.hatenablog.jp/"
  GithubID = "senyoltw"
  SpeakerDeckID = "senyoltw"
  TwitterID = "senyoltw"
  InstagramID = "senyoltw"
  TumblrURL = "https://senyoltw.tumblr.com/"
  BookmarkURL = "https://b.hatena.ne.jp/iuyui/bookmark"
  Name = "senyoltw"
  HeaderUsername = "senyoltw"
  HeaderHostname = "senyoltw.net"
  Email = "senyoltw@senyoltw.net"
  About = "せにょーる/senyoltw です。たまに本を読みます。たまにプログラムを書きます。"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"

